### ISSUE TITLE
如何让指示灯在烧录的时候，指示灯快速闪烁

### ISSUE THREAD

**Issue by xiaolongba** [RadioOperator/STM32F103C8T6_CMSIS-DAP_SWO#13]
Hello，RadioOperator

非常感谢您的贡献，基本上我将其移植到我自己的平台，并且可以很好地工作。但是，我想新增一个功能，即烧录的时候，PC13的指示灯可以快速闪烁，但是我尝试了下好像均无效。比如，我在`ID_DAP_Transfer`、`ID_DAP_SWD_Sequence`、`ID_DAP_TransferBlock`等事件中，将LED灯的模式设为：
> u8LedMode |= 0x02;  

然而，当我给对端设备烧录时，LED灯并没有闪烁。难道烧录时，这些事件都不会进来吗？不知道博主有没有什么经验这方面，能否分享下？

谢谢！

**Comment by RadioOperator** [comment]
这个我没有试过。

LED控制放在了SysTick中断里面，而0x02的快闪模式有一点特别，就是需要不停设置，您再试一试，可以看看UART是怎么触发快闪的。 不好意思，我没有时间自己试。

**Comment by xiaolongba** [comment]
UART接收回调，就是设个LED模式就完事了。后来发现是优化等级太高，导致设了模式无效。不优化就没事了😂``
