### ISSUE TITLE
keilv5工程编译失败

### ISSUE THREAD

**Issue by Asgiftia** [RadioOperator/STM32F103C8T6_CMSIS-DAP_SWO#14]
楼主您好，我是用keilv5编译工程发现报出大量头文件缺失的情况，部分已经根据您之前的issue，将v5路径加入解决，但还存在以下头文件无法找到
USB\usb_config.c(521): error:  #5: cannot open source input file "usb_lib.c": No such file or directory
USB\usbd_STM32F103.c(16): error:  #5: cannot open source input file "RTL.h": No such file or directory
![image](https://github.com/RadioOperator/STM32F103C8T6_CMSIS-DAP_SWO/assets/102196525/8551f3e1-ae67-446f-9b71-ce7c86202d62)
同时打开工程时无法加载USB_CM3.lib文件
![image](https://github.com/RadioOperator/STM32F103C8T6_CMSIS-DAP_SWO/assets/102196525/1806c6bd-fdeb-452e-b50e-b46af9cc1803)
请问，是不是此工程在v5下无法编译，需要v4下进行编译，感谢解答

**Comment by RadioOperator** [comment]
refer to this：

https://www.stmcu.org.cn/module/forum/forum.php?mod=viewthread&tid=616081&extra=&highlight=f103c8&page=1
https://shequ.stmicroelectronics.cn/thread-616081-1-1.html

**Comment by Asgiftia** [comment]
楼主您好，我已经根据您提供的链接完成配置，目前编译完成，感谢。
关于cmsis-dap，目前官方提供的代码不管是cmsisi还是daplink都是基于rtos进行开发，楼主您有做过相关的工程吗？😊

**Comment by RadioOperator** [comment]
> 楼主您好，我已经根据您提供的链接完成配置，目前编译完成，感谢。 关于cmsis-dap，目前官方提供的代码不管是cmsisi还是daplink都是基于rtos进行开发，楼主您有做过相关的工程吗？😊

有用RTOS的：
https://github.com/RadioOperator/CMSIS-DAP_for_STLINK-V3MINI

**Comment by Asgiftia** [comment]
好的感谢，我研究一下😃
