### ISSUE TITLE
请问好像编译缺少头文件

### ISSUE THREAD

**Issue by nxp1768** [RadioOperator/STM32F103C8T6_CMSIS-DAP_SWO#4]
缺少Driver_USART.h 文件，可否加上。
我想用这个仿真器测试IAR的A7多核调试。在网上找到一个版本，编译可以通过，sw功能正常，jtag无法使用

**Comment by RadioOperator** [comment]
@nxp1768 不缺，这个Driver_USART.h 文件，是ARM CMSIS的系统文件，位置在
C:\Keil\ARM\PACK\ARM\CMSIS\5.3.0\CMSIS\Driver\Include
看一看Doc文件夹，里面有一些要求的。

我这个CMSIS-DAP，有JTAG功能，我在Keil里面测试过的。
不知您用什么硬件，有问题告诉我。

**Comment by nxp1768** [comment]
感谢回复。编译问题解决。安装ARM CMSIS后解决了。我用的板子是NANO－PI，主芯片为全志H3 四核A7。开发环境为IAR（裸奔，没有上系统）。目前可他通过JTAG加载到SDRAM运行。速度不能高于1M。但是memory读回的内存数据是错的。

**Comment by RadioOperator** [comment]
memory读回的内存数据是错的? 希望您能查明原因，CMSIS-DAP的核心部分没有动过。
大多数人都是用在Cortex-M上面，A7不多，不知道是不是与这个有关。您手上如果有J-Link的话，可以对比一下。还有，CMSIS-DAP应该只是个桥梁，控制软件（IAR，Keil，....）也有关系。
速度问题，如果您使用BluePill板的话，由于数据线没有抗干扰措施，很容易受到目标板系统的干扰，解决办法是在每条数据线上面串联一个100欧姆的电阻。如果使用STLINK板子来改，就会稳定一些，原板有几条线已经有电阻了。

**Comment by nxp1768** [comment]
JLINK我测试过，比较稳定一切都对的，在IAR环境下JLINK不支持多核调试。应该是工具使用问题。我再继续摸索下。感谢您开源的代码。

**Comment by RadioOperator** [comment]
不用客气。
