### ISSUE TITLE
CMSIS-DAP CDC driver

### ISSUE THREAD

**Issue by techtoys** [RadioOperator/STM32F103C8T6_CMSIS-DAP_SWO#8]
Successfully compiled and downloaded STM32F103C8T6DAP project to BOARD_V2.

Using Windows 7 PRO under Device Manager > Other devices showing an unknown device `CMSIS-DAP CDC`. I have tried automatic driver search over the internet but it failed. That means the CDC driver is not installed. 

Is there any way to solve the issue?

**Comment by RadioOperator** [comment]
Hi, thanks for you tell me the problem.
I changed the USB VID&PID, and forgot to update the USB driver for Windows 7.
Now, please try to install/update your USB driver for VCP using:
https://github.com/RadioOperator/STM32F103C8T6_CMSIS-DAP_SWO/tree/master/Doc/Win7-VCP-Driver
and tell me if the issue solved.

**Comment by techtoys** [comment]
@RadioOperator changed the USB VID&PID
Yes, it works. Thank you. I also tried some other VID and PID combinations like VID set to 0xC251 and PID set 0xF001 to match KEIL, Inc. The project recompiled and downloaded to an STM32F103CBT6 with Preprocessor options changed to STLINK_V21. The Window7 driver is working by matching the VID and PID to 0xC251 and 0XF001, respectively.

The original one is for STM but CMSIS-DAP is released by ARM, although the MCU is an STM32F103xxx. In this case, should we use KEIL's or ST's VID?

**Comment by RadioOperator** [comment]
@techtoys  Thanks.
To you personal, using KEIL's or ST's VID wouldn't be a problem, I think.
If you want to use the code in a product, you have to apply your company VID code from USB org.

I also agree we use ARM CMSIS-DAP source code to build the device, we could use ARM VID for testing. But ARM's engineer asked me to use STM or others before....refer to:
https://github.com/ARM-software/CMSIS_5/issues/389#issuecomment-566480505

Btw, my current used VID/PID, not registered/informed from/to STM, also for testing only.

**Comment by techtoys** [comment]
@RadioOperator If you want to use the code in a product, you have to apply your company VID code from USB org.
That will involve a certain amount of money, like US$5,000? By googling, I find http://pid.codes/about/ which seems good for small companies too.

**Comment by RadioOperator** [comment]
@techtoys  Yes.  http://pid.codes/ , maybe a good alternative.

**Comment by techtoys** [comment]
Good. Thanks.
